chunk.defaultWidth=5
chunk.defaultHeight=5
chunk.defaultLayers=2

chunkWidthRadius=5
chunkHeightRadius=3

scene.width=37
scene.height=20
scene.layers=2
scene.delta=1

staticPlaneContainer.defaultWidth=100
staticPlaneContainer.defaultHeight=100
staticPlaneContainer.layers=2

block.defaultFriction=0.9f
block.defaultRestitution=0.1f

player.width=0.8f
player.height=1.8f
player.density=2f
player.friction=1.3f
player.restitution=0.1f
player.defaultEquipmentCapacity=50

playerActivator.maxPlayersRadius=0.99f

physics.timeStep=0.02f
physics.velocityIterations=8
physics.positionIterations=4

leftClickDelay=200
missingTexturePath=missing.png

TCPPort=54555
UDPPort=54777

moveImpulseX=1f
maxPlayerVelocityX=5f
playerJumpStrength=20f
